config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
	resources :users do
		member do
			get "profile"
			post "status"

			get "profile/edit" => "users#edit"
		end

		collection do
			post "follow"
		end
	end

	root "pages#home"
	
	get "/home" => "pages#home"
	get "/admin" => "pages#admin"

	get "/about" => "pages#about"
	get "/contact" => "pages#contact"
	get "/faq" => "pages#faq"
	get "/privacy" => "pages#privacy"
	
	post "/withdraw" => "pages#withdraw"

	resources :videos do
		collection do
			get "setting"
			get "favourite"

			get "spoop_of_the_month"
			get "spoop_of_the_year"
			
			get "flagged"

			post "rate"

			get "search"
		end

		member do
			get "like"
			
			get "report_abuse"
			get "remove_abuse_flag"
		end
	end

	resources :comments

	resources :themes
	
	resources :messages do
		collection do
			get "inbox"
			get "sent"
			get "trash"
		end
	end
	
	resources :pledges do
		collection do
			get "cart"
			post "charges"
		end
	end

	resources :subscriptions

	resources :channels do
		member do
			get "subscribe"
		end
	end

	resources :user_status_comments

	resources :user_statuses do
		member do
			get "like"
			get "share"
		end
	end
end

app/models/theme.rb
class Theme < ActiveRecord::Base
	has_and_belongs_to_many :videos
end

app/controllers/themes_controller.rb
require "will_paginate/array"
class ThemesController < ApplicationController
	before_action :set_theme, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_admin!, :except => [:show]

    skip_before_action :authenticate_user!, :only => [:show]

	def index
		@themes = Theme.all
	end

	def show
		@videos = @theme.videos.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@theme = Theme.new
	end

	def edit
	end

	def create
		@theme = Theme.new(theme_params)

		respond_to do |format|
			if @theme.save
				format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
				format.json { render :show, status: :created, location: @theme }
			else
				format.html { render :new }
				format.json { render json: @theme.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @theme.update(theme_params)
				format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
				format.json { render :show, status: :ok, location: @theme }
			else
				format.html { render :edit }
				format.json { render json: @theme.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@theme.destroy
		respond_to do |format|
			format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	def set_theme
		@theme = Theme.find(params[:id])
	end

	def theme_params
		params.require(:theme).permit(:name, :html_class)
	end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<div class="row">
	<div class="col-xs-4 col-xs-offset-4">
		<%= form_for(@theme) do |f| %>

			<ul class="text-danger">
				<% @theme.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>

			<div class="form-group">
				<%= f.text_field :name, :placeholder => "Theme Name", :class => "form-control" %>
			</div>
			<div class="form-group">
				<%= f.text_field :html_class, :placeholder => "Theme Icon Class", :class => "form-control" %>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary form-control"> Create Theme </button>
			</div>
		<% end %>
	</div>
</div>

app/views/themes/edit.html.erb
<h2 class="text-center"> Edit theme </h2>

<%= render "form" %>

<%= link_to "List All Theme", themes_path %>

app/views/themes/index.html.erb
<h2 class="text-center"> All Themes </h2>

<div class="row table-responsive">
	<div class="col-md-4 col-md-offset-4">
		<table class="table table-striped">
			<thead>
				<tr>
					<th> Name </th>
					<th>  </th>
					<th>  </th>
				</tr>
			</thead>

			<tbody>
				<% @themes.each do |theme| %>
					<tr>
						<td><%= theme.name %></td>
						<td><%= link_to "Edit", edit_theme_path(theme) %></td>
						<td><%= link_to "Destroy", theme, method: :delete, data: { confirm: "Are you sure?" } %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<%= link_to "Create New Theme", new_theme_path %> <br>
<%= link_to "Admin Area", admin_path %>

app/views/themes/new.html.erb
<h2 class="text-center"> New theme </h2>

<%= render "form" %>

<%= link_to "List All Theme", themes_path %>

app/views/themes/show.html.erb
<div class="row calender widget-shadow"> 
	<div class="col-lg-10 col-md-12 col-sm-12">
		<h3 class="title"> <%= @theme.name %> </h3>

		<% @videos.each do |video| %>

			<div class="card cards">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12">
						<div class="col-lg-4 col-md-12 col-sm-12 text-center">
							<figure>
								<a href="<%= video_path(video) %>">
									<img src="<%= video.video.url(:medium) %>" alt="" class="dummy img-responsive">
								</a>
							</figure>
						</div>
						<div class="col-lg-8 col-md-12 col-sm-12 porro">
							<h4>
								<a href="<%= video_path(video) %>">
									<%= video.title %>
								</a>
							</h4>
							<p>
								<strong>About: </strong> <%= video.description %>
							</p>
							<p>
								<strong>Views: </strong>
								<span class="fa fa-user"></span>
								<span class="tags"> <%= video.impressionist_count(:filter => :session_hash) %> </span>
							</p>
							<p>
								<strong> Upload: </strong>
								<span class="fa fa-clock-o"></span>
								<span class="tags"> <%= timeago(video.created_at) %> </span>
							</p>

							<p>
								<strong>Rating: </strong>
								<span id="stars-default" class="rating-bar" data-rating="<%= video.total_rating %>">
									<input type=hidden name"rating">
								</span>
							</p>
							<p>
								<strong>Subscribe: </strong>
								<span class="fa fa-envelope"></span>
								<span class="tags"> <%= video.user.being_followed_by.length %> </span>
							</p>
							<div class="comment">
								<strong>Comment: </strong>
								<span class="price-text-color fa fa-comment"></span>
								<span class="tags"> <%= video.comments.length %> </span>
							</div>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

<%= render :partial => "layouts/pagination", :locals => {:collection => @videos} unless @videos.empty? %>