config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
	resources :users do
		member do
			get "profile"
			post "status"

			get "profile/edit" => "users#edit"
		end

		collection do
			post "follow"
		end
	end

	root "pages#home"
	
	get "/home" => "pages#home"
	get "/admin" => "pages#admin"

	get "/about" => "pages#about"
	get "/contact" => "pages#contact"
	get "/faq" => "pages#faq"
	get "/privacy" => "pages#privacy"
	
	post "/withdraw" => "pages#withdraw"

	resources :videos do
		collection do
			get "setting"
			get "favourite"

			get "spoop_of_the_month"
			get "spoop_of_the_year"
			
			get "flagged"

			post "rate"

			get "search"
		end

		member do
			get "like"
			
			get "report_abuse"
			get "remove_abuse_flag"
		end
	end

	resources :comments

	resources :themes
	
	resources :messages do
		collection do
			get "inbox"
			get "sent"
			get "trash"
		end
	end
	
	resources :pledges do
		collection do
			get "cart"
			post "charges"
		end
	end

	resources :subscriptions

	resources :channels do
		member do
			get "subscribe"
		end
	end

	resources :user_status_comments

	resources :user_statuses do
		member do
			get "like"
			get "share"
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# , :lockable, :timeoutable
	devise :database_authenticatable, :registerable, :confirmable,
		:recoverable, :rememberable, :trackable, :validatable, :omniauthable,
		:omniauth_providers => [:facebook, :google_oauth2]

	has_attached_file :photo,
		styles: {
			medium: "300x300>",
			thumb: "100x100>"
		}
	validates_attachment :photo, content_type: { content_type: /\Aimage\/.*\Z/ }

	has_attached_file :banner,
		styles: {
			medium: "850x280>",
			thumb: "400x400>"
		}
	validates_attachment :banner, content_type: { content_type: /\Aimage\/.*\Z/ }

	validates :username, :uniqueness => true, :presence => true, :allow_nil => false
	validates :name, :presence => true, :allow_nil => false

	has_many :identities

	has_one :channel

	has_many :videos
	has_many :video_likes
	
	has_many :comments

	has_many :ratings

	has_many :pledges
	
	has_many :transactions
	
	has_many :subscriptions

	has_many :sent_messages, :class_name => "Message", :foreign_key => "sender_id"
	has_many :received_messages, :class_name => "Message", :foreign_key => "recipient_id"

	has_many :user_statuses
	has_many :user_status_likes
	has_many :user_status_shares

	has_many :user_status_comments

	def self.find_or_create(auth)
		email = auth.info.email
		user = User.where(:email => email).first_or_initialize

		user.name ||= auth.info.name
		user.username ||= user.name.split(" ").first
		user.photo ||= open(auth.info.image, :allow_redirections => :safe)

		unless user.persisted?
			generated_password = Devise.friendly_token.first(8)
			user.password = generated_password
			user.password_confirmation = generated_password

			user.confirmed_at = DateTime.now
		end

		user.save

		user
	end

	def being_followed_by
		User.find (UserFollowing.where(:user_id => self.id).map(&:followed_by).uniq)
	end

	def following_other_users
		User.find (UserFollowing.where(:followed_by => self.id).map(&:user_id).uniq)
	end

	def self.subscribed_users
		all.select{|user| user.has_active_subscription?}
	end

	def self.subscribed_users_videos
		subscribed_users.collect{|user| user.videos}.flatten
	end

	def unpaid_pledges
		pledges.where(:paid => false)
	end

	def unpaid_pledges_amount
		unpaid_pledges.sum(:amount).round(2)
	end

	def paid_pledges
		pledges.where(:paid => true)
	end

	def paid_pledges_amount
		paid_pledges.sum(:amount).round(2)
	end

	def mark_unpaid_pledges
		pledges = self.pledges.where(:paid => false)

		pledges.each do |pledge|
			Transaction.create!(:user_id => pledge.video.user.id, :pledge_id => pledge.id, :amount => pledge.amount, :credit => true, :description => "Video pledged...")
		end

		pledges.update_all(:paid => true)
	end

	def money_owned
		transactions.where(:credit => true).sum(:amount) - transactions.where(:withdraw => true).sum(:amount)
	end

	def money_owned_after_system_deduction
		total_money = money_owned

		retention = total_money * SETTINGS_CONFIG[:retention_percentage].to_f.round(2) / 100
		remaining = total_money - retention - SETTINGS_CONFIG[:stripe_withdraw_fee].to_f.round(2)

		total_money == 0 ? total_money : remaining.round(2)
	end

	def add_debit_amount(amount)
		Transaction.create!(:user_id => self.id, :amount => amount, :debit => true, :withdraw => true, :description => "Withdraw amount")
	end

	def has_active_subscription?
		subscriptions.where(:active => true).length > 0
	end

	def have_subscription_money?
		self.money_owned >= SETTINGS_CONFIG[:spooph_subscription_fee].to_f.round(2)
	end

	def after_confirmation
		user = self
		today = Date.today

		days = SETTINGS_CONFIG[:free_subscription_duration].to_i.days
		subscription = Subscription.create!(:user_id => user.id, :start => today, :end => today + days)
		SubscriptionMailer.free_subscription(subscription)

		Channel.create!(:name => user.username, :user_id => user.id)
	end

	def recently_viewed_videos
		videos = []
		video_ids = Impression.where(:user_id => self.id).order("created_at desc").map(&:impressionable_id).uniq

		unless video_ids.empty?
			videos = Video.find(video_ids)

			videos = video_ids.collect{|id| videos.select{|video| video.id == id}.first }
		end

		videos.flatten
	end

	def personal_statuses
		self.user_statuses.order("created_at desc")
	end

	def user_shared_statuses
		self.user_status_shares.collect{|share| share.user_status.status_date = share.created_at and share.user_status}.sort{|a, b| b.status_date <=> a.status_date}
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:profile, :update]

	def profile
	end

	def edit
		@user = current_user
	end

	def update
		if params[:user][:photo]
			@user.photo = params[:user][:photo]
		end

		if params[:user][:banner]
			@user.banner = params[:user][:banner]
		end

		if (!params[:user][:password].empty?) and params[:user][:password_confirmation] and params[:user][:password] == params[:user][:password_confirmation]
			@user.password = @user.password_confirmation = params[:user][:password]
		end

		@user.assign_attributes(user_params)

		respond_to do |format|
			if @user.save
				sign_in(@user, :bypass => true)
				format.html { redirect_to profile_user_path(@user), notice: 'Your profile has been successfully updated.' }
			else
				format.html { render :edit }
			end
		end
    end

	def follow
		follow = UserFollowing.where(follow_params).first_or_initialize
		follow.save!

		respond_to do |format|
			format.html { redirect_to profile_user_path(follow.user_id), notice: "Success" }
		end
	end

	def status
		status = UserStatus.new(user_status_params)
		status.save! unless status.body.squish.empty?

		redirect_to profile_user_path(current_user)
	end

	private
	def set_user
		@user = User.find(params[:id])
	end

	def follow_params
		params.permit(:user_id).merge(:followed_by => current_user.id)
	end

	def user_status_params
		params.permit(:body).merge(:user_id => current_user.id)
	end

	def user_params
		params.require(:user).permit(:username, :name, :bio, :account, :routing_number, :country)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_following_form.html.erb
<%= form_tag follow_users_path do %>
	<input type="hidden" name="user_id" value="<%= user.id %>">
	<button class="btn btn-sm btn-default btn-block bgs">
		<span class="fa fa-plus-circle"></span> Follow
	</button>
<% end %>

app/views/users/_user_shared_statuses.html.erb
<div class="feed-text-full">

	<% user.user_shared_statuses.each do |status| %>

		<div class="feed-text-single">
			<div class="feed-text-single-header">
				<a href="<%= profile_user_path(status.user) %>">
					<img src="<%= status.user.photo.url(:thumb) %>" alt="">
				</a>
				<a href="<%= profile_user_path(status.user) %>">
					<h4> <%= status.user.name %> </h4>
				</a>
				<p class="small-font-size"> <%= timeago(status.created_at) %> </p>
			</div>
			<div class="feed-text-single-content">
				<p> <%= status.body.html_safe %> </p>
			</div>
			<div class="feed-text-single-footer">
				<a href="<%= like_user_status_path(status) %>" class="status-like-button">
					<i class="fa fa-heart"></i> <%= status.total_likes %> Likes
				</a>
				
				<a class="pop-click" data-popup-open="popup-status-comment-<%= status.id %>">
					<i class="fa fa-comment"></i>
					Comment
				</a>
				<% if @user != current_user %>
					<a href="<%= share_user_status_path(status) %>">
						<i class="fa fa-share"></i>
						Share
					</a>
				<% end %>
			</div>
		</div>	

		<%= render :partial => "user_status_comments/comments_popup", :locals => {:status => status} %>
	<% end %>
</div>

app/views/users/_user_statuses.html.erb
<div class="feed-text-full">

	<% user.personal_statuses.each do |status| %>

		<div class="feed-text-single">
			<div class="feed-text-single-header">
				<a href="<%= profile_user_path(status.user) %>">
					<img src="<%= status.user.photo.url(:thumb) %>" alt="">
				</a>
				<a href="<%= profile_user_path(status.user) %>">
					<h4> <%= status.user.name %> </h4>
				</a>
				<p class="small-font-size"> <%= timeago(status.created_at) %> </p>
			</div>
			<div class="feed-text-single-content">
				<p> <%= status.body.html_safe %> </p>
			</div>

			<% if current_user.has_active_subscription? %>
				<div class="feed-text-single-footer">
					<a href="<%= like_user_status_path(status) %>" class="status-like-button">
						<i class="fa fa-heart"></i> <%= status.total_likes %> Likes
					</a>
					
					<a class="pop-click" data-popup-open="popup-status-comment-<%= status.id %>">
						<i class="fa fa-comment"></i>
						Comment
					</a>
					<% if @user != current_user %>
						<a href="<%= share_user_status_path(status) %>">
							<i class="fa fa-share"></i>
							Share
						</a>
					<% end %>
				</div>
			<% end %>
		</div>	

		<%= render :partial => "user_status_comments/comments_popup", :locals => {:status => status} %>
	<% end %>
</div>

app/views/users/_withdraw_form.html.erb
<div class="popup popup-withdraw" data-popup="popup-withdraw-<%= user.id %>">
	<div class="popup-close-overlay" data-popup="popup-withdraw-<%= user.id %>" data-popup-close="popup-withdraw-<%= user.id %>">
	</div>
	<div class="popup-outer">
		<div class="popup-inner">
			<div class="main-page login-page ">
				<h3 class="title1">
					Withdraw Money
				</h3>

				<div class="login-top"></div>
				<div class="widget-shadow">
					<div class="login-body">
						<%= form_tag(withdraw_path, :method => "post") do %>

							<%= text_field_tag :amount, "", :placeholder => "Amount (in dollar)" %>

							<button class="btn btn-success form-control">
								<span class="fa fa-university"></span> Withdraw
							</button>
						<% end %>
					</div>
				</div>
			</div>

			<a class="popup-close" data-popup-close="popup-withdraw-<%= user.id %>">x</a> 
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="">
	<h3 class="title1"> Edit Profile </h3>
	<div class="fb-profile">

		<%= form_for(@user, :html => { :multipart => true }) do |f| %>
		
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="cover-photo-area">
					<img align="left" class="fb-image-lg" src="<%= @user.banner.url%>" alt="Profile image example">

					<%= f.file_field :banner %>
					<p>Change Cover Photo</p>
				</div>
			</div>

			<div class="col-lg-4 col-md-4 col-sm-12">
				<div class="profile-thumb-area">
					<img align="left" class="fb-image-profile fb-image-profile-edit thumbnail" src="<%= @user.photo.url %>" alt="Profile image example">

					<%= f.file_field :photo %>
					<p align="center"> Change Profile Picture </p>

					<%= f.text_area :bio, :class => "form-control", :row => "3", :placeholder => "You can update your bio here...", :style => "resize:none;" %>
				</div>
			</div>

			<div class="col-lg-4 col-md-4 col-sm-12">
				<div class="form-group">
					<label for="user_name"> Name </label>
					<%= f.text_field :name, :class => "form-control" %>
				</div>

				<div class="form-group">
					<label for="user_username"> Username </label>
					<%= f.text_field :username, :class => "form-control" %>
				</div>

				<div class="form-group">
					<span class="small-font-size text-danger">
						<%= @user.errors.full_messages_for(:password).first %>
					</span>
					<label for="user_password"> Password </label>
					<%= f.password_field :password, :class => "form-control" %>
				</div>

				<div class="form-group">
					<label for="user_password_confirmation"> Confirm your password </label>
					<%= f.password_field :password_confirmation, :class => "form-control" %>
				</div>

			<hr>
			<h4> Bank Information: </h4> <br>

			<div class="form-group">
				<label for="user_account"> Account Number </label>
				<%= f.text_field :account, :class => "form-control" %>
			</div>

			<div class="form-group">
				<label for="user_routing_number"> Routng Number </label>
				<%= f.text_field :routing_number, :class => "form-control" %>
			</div>

			<div class="form-group">
				<label for="user_country"> Country </label>
				<%= f.text_field :country, :class => "form-control" %>
			</div>

			<br/>
			<br/>
				<p align="center">
					<button name="save" class="btn btn-sm btn-success col-sm-4" type="submit">
						<i class="fa fa-save"></i> 
						&nbsp;&nbsp;Save
					</button>
					
					&nbsp;&nbsp;
					
					<a href="<%= profile_user_path(@user) %>" class="btn btn-sm btn-default">
						<i class="fa fa-close"></i>
						&nbsp;&nbsp;Cancel
					</a>
				</p>
			</div>
		<% end %>
	</div>
</div>

app/views/users/profile.html.erb
<h3 class="title1"> Profile Page </h3>
<div class="fb-profile">
	<img align="left" class="fb-image-lg" src="<%= @user.banner.url%>" alt="Profile image example">
	<img align="left" class="fb-image-profile thumbnail" src="<%= @user.photo.url if @user.photo %>">

	<div class="fb-profile-text">
		<h4> <%= @user.name %> </h4>
		<p class="small-font-size">
			Followed By: <%= @user.being_followed_by.length %>
			<br>
			Following: <%= @user.following_other_users.length %>
		</p>
		<p class="pro-bio">
			<%= @user.bio %>
		</p>
	</div>
</div>

<div class="well">
	<div class="media">

		<% if @user != current_user and current_user.has_active_subscription? %>
			<div class="col-md-2 col-xs-2">
				<button class="btn btn-sm btn-success pop-click" data-popup-open="popup-message-<%= @user.id %>">
					<i class="fa fa-envelope"></i> &nbsp; Message
				</button>
				<%= render :template => "messages/new", :locals => {:user => @user } if current_user %>
			</div>

			<div class="col-md-3 col-xs-3">
				<%= render :partial => "users/following_form", :locals => {:user => @user } if current_user %>
			</div>
		<% end %>
		<% if @user == current_user %>
			<div class="col-md-3 col-xs-3" style="padding: 6px !important;">
				Total Amount Owned:
				<i class="fa fa-dollar"></i> <%= @user.money_owned_after_system_deduction %>
			</div>
			<div class="col-md-2 col-xs-2">
				<button class="btn btn-sm btn-success pop-click" data-popup-open="popup-withdraw-<%= @user.id %>">
					Withdraw
				</button>
				<%= render :partial => "users/withdraw_form", :locals => {:user => @user } %>
			</div>
		<% end %>

		<div class="col-md-7 col-xs-7">
			<% if @user == current_user %>
				<span class="pull-right a-pro-btn2">
					<a href="<%= profile_edit_user_path(current_user) %>">
						<button class="btn btn-sm btn-success " type="button" data-toggle="tooltip" data-original-title="Edit this user">
							<i class="fa fa-edit"></i> &nbsp; Edit
						</button>
					</a>
				</span>
			<% end %>
		</div>
	</div>
</div>


<%= render :template => "user_statuses/user_status_list", :locals => {:user => @user} if current_user.has_active_subscription? %>

<%= render :partial => "videos/fresh_uploads", :locals => {:fresh_videos => @user.videos} %>