config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
	resources :users do
		member do
			get "profile"
			post "status"

			get "profile/edit" => "users#edit"
		end

		collection do
			post "follow"
		end
	end

	root "pages#home"
	
	get "/home" => "pages#home"
	get "/admin" => "pages#admin"

	get "/about" => "pages#about"
	get "/contact" => "pages#contact"
	get "/faq" => "pages#faq"
	get "/privacy" => "pages#privacy"
	
	post "/withdraw" => "pages#withdraw"

	resources :videos do
		collection do
			get "setting"
			get "favourite"

			get "spoop_of_the_month"
			get "spoop_of_the_year"
			
			get "flagged"

			post "rate"

			get "search"
		end

		member do
			get "like"
			
			get "report_abuse"
			get "remove_abuse_flag"
		end
	end

	resources :comments

	resources :themes
	
	resources :messages do
		collection do
			get "inbox"
			get "sent"
			get "trash"
		end
	end
	
	resources :pledges do
		collection do
			get "cart"
			post "charges"
		end
	end

	resources :subscriptions

	resources :channels do
		member do
			get "subscribe"
		end
	end

	resources :user_status_comments

	resources :user_statuses do
		member do
			get "like"
			get "share"
		end
	end
end

app/models/video.rb
class Video < ActiveRecord::Base

	is_impressionable :counter_cache => true, :column_name => :impressions_count

	has_attached_file :video,
	styles: {
		:thumb => {
			:geometry => "125x100",
			:format => "jpeg",
			:time => 10
		},
		:medium => {
			:geometry => "250x200",
			:format => "jpeg",
			:time => 10
		},
		:large => {
			:geometry => "600x350",
			:format => "jpeg",
			:time => 10
		}
	},
	:processors => [:transcoder]

	# validates_attachment_content_type :video, :content_type => ["application/x-shockwave-flash", "application/x-shockwave-flash", "application/flv", "video/x-flv", "video/mp4", "video/mpeg", "video/webm", "video/avi", "video/ogg", "video/x-divx", "video/divx"]
	validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/

	validates_attachment_presence :video

	validates_presence_of :title

	belongs_to :user
	validates_presence_of :user_id

	has_many :video_likes

	belongs_to :channel

	has_and_belongs_to_many :themes

	has_many :comments
	has_many :ratings
	
	has_many :pledges

	has_many :video_subscriptions

	scope :spooph_of_the_month_videos, -> { where(:spooph_of_the_month => true) }
	scope :spooph_of_the_year_videos, -> { where(:spooph_of_the_year => true) }
	scope :reported_videos, -> { where(:reported => true) }

	validate :check_video_duration, :on => :create
	validate :trim_description, :on => :create
	validate :add_channel, :on => :create
	after_create :notify_subscribed_users

	def check_video_duration
		if self.video.queued_for_write[:original]

			properties = `ffmpeg -i #{self.video.queued_for_write[:original].path} 2>&1`
			duration_details = properties.match("Duration: ([0-9]+):([0-9]+):([0-9]+).([0-9]+)")
			
			duration = 1000
			duration = duration_details[1].to_i * 3600 + duration_details[2].to_i * 60 + duration_details[3].to_i if duration_details

			if not self.user.has_active_subscription? and not (30..60).include?(duration)
				errors.add(:video, " duration should be in between 30 seconds to 60 seconds")
			end

			if self.user.has_active_subscription? and not (30..180).include?(duration)
				errors.add(:video, " duration should be in between 30 seconds to 180 seconds")
			end

			self.duration = Time.at(duration).utc.strftime("%H:%M:%S")
		else
			errors.add(:video, " can't be blank")
		end
	end

	def trim_description
		self.description = self.description.strip
	end

	def add_channel
		self.channel = self.user.channel
	end

	def notify_subscribed_users
		users = self.user.being_followed_by
		users.each do |user|
			SubscriptionMailer.new_video_notification(self, user)
		end
	end

	def total_views
		self.impressionist_count(:filter => :session_hash)
	end

	def total_rating
		self.ratings.length == 0 ? 0 : (self.ratings.sum(:rate) / self.ratings.length).to_i
	end

	def total_comments
		self.comments.length
	end

	def self.most_viewed_videos
		Video.order(:impressions_count => :desc)
	end

	def self.search(param)
		where("title LIKE ? OR description LIKE ?", "%#{param}%", "%#{param}%")
	end

	def self.spooph_of_the_month
		previous_month = Date.today - 1.month
		start_date = previous_month.beginning_of_month
		end_date = previous_month.end_of_month
		
		impression = Impression.where(:created_at => start_date..end_date).group("impressionable_id").order("COUNT(*) DESC").limit(1).first
		if impression
			video = Video.find(impression.impressionable_id)
			video.update(:spooph_of_the_month => true)
		end
	end

	def self.spooph_of_the_year
		previous_year = Date.today - 1.year
		start_date = previous_year.beginning_of_year
		end_date = previous_year.end_of_year

		video = Video.spooph_of_the_month_videos.where(:created_at => start_date..end_date).order("impressions_count DESC").limit(1).first
		video.update(:spooph_of_the_year => true) if video
	end

	def self.remove_old_videos
		today = Date.today
		Video.all.each do |video|
			next if video.spooph_of_the_year

			time_diff = Time.diff(today, video.created_at)

			if video.spooph_of_the_month
				video.destroy if time_diff[:day] >= SETTINGS_CONFIG[:spooph_of_the_month_duration].to_i
			else
				video.destroy if not video.user.has_active_subscription? and time_diff[:day] > SETTINGS_CONFIG[:free_subscription_duration].to_i
				video.destroy if video.user.has_active_subscription? and time_diff[:day] > SETTINGS_CONFIG[:paid_subscription_duration].to_i
			end
		end
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :set_video, only: [:show, :edit, :update, :destroy, :report_abuse, :remove_abuse_flag, :like]
	before_action :authenticate_admin!, :only => [:flagged, :remove_abuse_flag]

	skip_before_action :authenticate_user!, :only => [:show, :search, :spoop_of_the_month, :spoop_of_the_year]
	skip_before_action :verify_authenticity_token, :only => :rate

	def show
		@main_video = @video

		impressionist(@main_video, "video hit") if @main_video
		
		@right_panel_videos = Video.all - [@main_video]
		@recently_viewed_videos = current_user ? current_user.recently_viewed_videos : []
		@fresh_videos = Video.last(8)

		render "pages/home"
	end

	def edit
	end

	def create
		@video = Video.new(video_params)
		@video.themes << themes_collection

		respond_to do |format|
			if @video.save
				format.html { redirect_to video_path(@video), notice: "Video was successfully uploaded." }
			else
				@new_video = @video
				format.html { render :new }
			end
		end
	end

	def update
		respond_to do |format|
			if (@video.user == current_user || current_user.admin) and @video.update(video_params)
				format.html { redirect_to @video, notice: "Video was successfully updated." }
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		@video.destroy if @video.user == current_user || current_user.admin
		redirect_path = current_user.admin ? flagged_videos_path : setting_videos_path
		respond_to do |format|
			format.html { redirect_to redirect_path, notice: "Video was successfully destroyed." }
		end
	end

	def search
		query = params[:query].strip
		@videos = Video.search(query).paginate(:page => params[:page], :per_page => 10)
	end

	def setting
		@videos = current_user.videos
	end

	def favourite
		@video_subscriptions = current_user.video_subscriptions
	end

	def spoop_of_the_month
		@videos = Video.spooph_of_the_month_videos
	end

	def spoop_of_the_year
		@videos = Video.spooph_of_the_year_videos
	end

	def report_abuse
		@video.update(:reported => true)
		NotificationMailer.notify_abuse_video(@video, current_user)

		flash[:notice] = "Video has been reported successfully"
		redirect_to video_path(@video)
	end

	def remove_abuse_flag
		@video.update(:reported => false) if @video

		redirect_to flagged_videos_path
	end

	def flagged
		@videos = Video.reported_videos
	end

	def rate
		rating = Rating.where(:user_id => rating_params[:user_id], :video_id => rating_params[:video_id]).first_or_initialize
		rating.update(rating_params)

		respond_to do |format|
			format.json { render :json => {:status => 200} }
		end
	end

	def like
		VideoLike.where(:user => current_user, :video => @video).first_or_create
		respond_to do |format|
			format.html { redirect_to @video, :notice => "You have successfully liked video"}
		end
	end

	private

	def set_video
		@video = Video.find(params[:id])
	end

	def video_params
		params.require(:video).permit(:title, :video, :description).merge(user_id: current_user.id)
	end

	def themes_collection
		themes_ids = params.require(:video).permit(:themes => [])
		themes_ids.empty? ? [] : Theme.find([themes_ids["themes"]])
	end

	def rating_params
		params.permit(:video_id, :rate).merge(user_id: current_user.id)
	end
end

app/helpers/videos_helper.rb
module VideosHelper
	def timeago(time)
		content_tag(:span, time.iso8601, title: time.iso8601, class: "timeago")
	end
end

app/views/videos/_form.html.erb
<div class="main-page login-page upload-page-popup">
	<h3 class="title1"> Upload Video </h3>
	<div class="login-top"></div>
	<div class="widget-shadow">
		<div class="login-body">

			<% random_id = SecureRandom.hex %>

			<%= content_tag :div, @new_video.errors.full_messages.first, class: "alert alert-success card" unless @new_video.errors.empty? %>

			<% if (not @new_video.errors.empty?) and @new_video.errors.full_messages.first.include?(" duration ") and current_user and (not current_user.has_active_subscription?) %>
				<div class="alert alert-success card">
					You can avail more features by subscribing Spooph. Click
					<a href="new_subscription_path"> <i> Spoophalicious </i> </a> to subscribe.
				</div>
			<% end %>

			<%= form_for(@new_video, :html => {:class => "upload-category"}) do |f| %>
				<% half = @themes.length / 2 %>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					<% @themes[0..half].each do |theme| %>

						<% theme_id_adjustment = theme.name.gsub(" ", "-") + "-" + random_id %>
						
						<div class="form-group">
							<input type="checkbox" name="video[themes][]" id="<%= theme_id_adjustment %>" autocomplete="off" value="<%= theme.id %>">
							<div class="btn-group">
								<label for="<%= theme_id_adjustment %>" class="btn btn-success">
									<span class="glyphicon glyphicon-ok"> </span> <span> </span>
								</label>
								<label for="<%= theme_id_adjustment %>" class="btn btn-default active">
									<%= theme.name %>
								</label>
							</div>
						</div>
					<% end %>
				</div>

				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					<% @themes[half + 1..-1].each do |theme| %>

						<% theme_id_adjustment = theme.name.gsub(" ", "-") + "-" + random_id %>

						<div class="form-group">
							<input type="checkbox" name="video[themes][]" id="<%= theme_id_adjustment %>" autocomplete="off" value="<%= theme.id %>">
							<div class="btn-group">
								<label for="<%= theme_id_adjustment %>" class="btn btn-success">
									<span class="glyphicon glyphicon-ok"> </span> <span> </span>
								</label>
								<label for="<%= theme_id_adjustment %>" class="btn btn-default active">
									<%= theme.name %>
								</label>
							</div>
						</div>
					<% end %>
				</div>
				
			
				<%= f.text_field :title, :placeholder => "Video Title", :class => "video-title" %>

				<%= f.text_area :description, :placeholder => "Video Description", :class => "form-control", :style => "resize: none;", :rows => "3" %>				
				<%= f.file_field :video, :class => "upload-video" %>

				<button class="btn btn-success sb-upload-btn">
					<span class="fa fa-upload"></span> Upload
				</button>
				<div class="clearfix"></div>
			<% end %>
		</div>
	</div>
</div>

app/views/videos/_fresh_uploads.html.erb
<div class="row calender widget-shadow">
	<div class=" col-lg-9 col-md-9 col-sm-9">
		<h3> New videos </h3>
	</div>
	<div class="col-md-3 col-sm-3">
		<div class="controls pull-right">
			<a id="prevButton" class="left fa fa-chevron-left btn btn-success"></a>
			<a id="playButton" class="left fa fa-play btn btn-success"></a>
			<a id="pauseButton" class="right fa fa-pause btn btn-success"></a>
			<a id="nextButton" class="right fa fa-chevron-right btn btn-success"></a>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12 col-md-12 col-sm-12">
		<div id="carousel-example1" class="carousel slide " data-ride="carousel">
			<div class="carousel-inner">

				<% fresh_videos.each_with_index do |video, index| %>

					<% open_top_tags = index == 0 || ((index + 1) % 5 == 0) %>
					<% close_bottom_tags = ((index + 1) % 4 == 0) || fresh_videos.length == index + 1 %>

					<% if open_top_tags %>
						<div class="item <%= "active" if index == 0 %>">
							<div class="row">
					<% end %>
								<div class="col-sm-3">
									<div class="col-item">
										<div class="photo">
											<a href="<%= video_path(video) %>">
												<img src="<%= video.video.url(:medium) %>" class="img-responsive" alt="a" />
											</a>
										</div>

										<div class="info">
											<div class="row">
												<div class="price col-md-6">
													<p>
														<span class="fa fa-eye"></span>
														<span class="tags"> <%= video.impressionist_count(:filter => :session_hash) %> </span>
													</p>
												</div>
												<div class="rating  col-md-6">
													<span id="stars-default" class="rating-bar" data-rating="<%= video.total_rating %>">
														<input type=hidden name"rating"/>
													</span>
												</div>
											</div>

											<div class="separator clear-left">
												<a href="<%= video_path(video) %>">
													<p>
														<i class="price-text-color fa fa-caret-square-o-right"></i>
														See Now
													</p>
												</a>
											</div>
											<div class="clearfix"> </div>
										</div>
									</div>
								</div>

						<% if close_bottom_tags %>
							</div>
						</div>
					<% end %>

				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/videos/_new_form.html.erb
<div class="popup popup-upload" data-popup="popup-upload">
	<div class="popup-close-overlay" data-popup="popup-upload" data-popup-close="popup-upload"> </div>
	<div class="popup-outer">
		<div class="popup-inner">
			<%= render :template => "videos/new", :locals => {:@new_video => Video.new } %>
			<a class="popup-close" data-popup-close="popup-upload">x</a> 
		</div>
	</div>
</div>

app/views/videos/_recent_views.html.erb
<div class="row calender widget-shadow">
	<div class=" col-lg-9 col-md-9 col-sm-9">
		<h3> Recent videos </h3>
	</div>
	<div class="col-md-3 col-sm-3">
		<div class="controls pull-right">
			<a id="prevButton" class="left fa fa-chevron-left btn btn-success"></a>
			<a id="playButton" class="left fa fa-play btn btn-success"></a>
			<a id="pauseButton" class="right fa fa-pause btn btn-success"></a>
			<a id="nextButton" class="right fa fa-chevron-right btn btn-success"></a>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12 col-md-12 col-sm-12">
		<div id="carousel-example1" class="carousel slide " data-ride="carousel">
			<div class="carousel-inner">

				<% recently_viewed_videos.each_with_index do |video, index| %>

					<% open_top_tags = index == 0 || ((index + 1) % 5 == 0) %>
					<% close_bottom_tags = ((index + 1) % 4 == 0) || recently_viewed_videos.length == index + 1 %>

					<% if open_top_tags %>
						<div class="item <%= "active" if index == 0 %>">
							<div class="row">
					<% end %>
								<div class="col-sm-3">
									<div class="col-item">
										<div class="photo">
											<a href="<%= video_path(video) %>">
												<img src="<%= video.video.url(:medium) %>" class="img-responsive" alt="a" />
											</a>
										</div>

										<div class="info">
											<div class="row">
												<div class="price col-md-6">
													<p>
														<span class="fa fa-eye"></span>
														<span class="tags"> <%= video.impressionist_count(:filter => :session_hash) %> </span>
													</p>
												</div>
												<div class="rating  col-md-6">
													<span id="stars-default" class="rating-bar" data-rating="<%= video.total_rating %>">
														<input type=hidden name"rating"/>
													</span>
												</div>
											</div>

											<div class="separator clear-left">
												<a href="<%= video_path(video) %>">
													<p>
														<i class="price-text-color fa fa-caret-square-o-right"></i>
														See Now
													</p>
												</a>
											</div>
											<div class="clearfix"> </div>
										</div>
									</div>
								</div>

						<% if close_bottom_tags %>
							</div>
						</div>
					<% end %>

				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/videos/_search_form.html.erb
<form class="input" method="get" action="<%= search_videos_path %>">
	<input class="sb-search-input" name="query" placeholder="Search..." type="search" id="input-31" />
	<button class="btn btn-success sb-search-btn" type="submit">
		<span class="fa fa-search"></span>
	</button>
</form>

app/views/videos/_video_stats.html.erb
<div class="row video-info">
	<div class="price col-md-2" style="padding-right: 0px;">
		<p>
			<span class="price-text-color fa fa-eye"></span>
			<span class="tags"> <%= video.total_views %> </span>
		</p>
	</div>

	<div class="price col-md-2" style="padding-right: 0px;">
		<a href="<%= like_video_path(video) %>">
			<span class="price-text-color fa fa-heart"></span>
			<span class="tags"> <%= video.video_likes.count %> </span>
		</a>
	</div>
	
	<div class="price col-md-2" style="padding-right: 0px;">
		<p>
			<%= render :partial => "pledges/form", :locals => {:video => video} %>
		</p>
	</div>

	<form action="" method="post" class="rate-this-video">
		<%= csrf_meta_tags %>

		<input type=hidden name="video" value="<%= video.id %>">
		<div class="rating col-md-2" style="padding-right: 0px;">
			<span id="stars-default" class="rating-bar" data-rating="<%= video.total_rating %>">
				<input type=hidden name="rating">
			</span>
		</div>
	</form>

	<div class="comment col-md-2" style="padding-right: 0px;">
		<p class="btn-details">
			<a class="pop-click front-comment-btn" data-popup-open="popup-comment">
				<span class="price-text-color fa fa-comment"></span> <%= video.total_comments %>
			</a>
		</p>
	</div>
	
	<div class="col-md-1" style="padding-right: 0px;">
		<a href="<%= report_abuse_video_path(video) %>">
			<span class="text-danger fa fa-flag"></span>
		</a>
	</div>

	<div class="share-front col-md-1" style="padding-right: 0px;">
		<a class="pop-click" data-popup-open="popup-share">
			<span class="price-text-color fa fa-share-alt"></span>
		</a>

		<%= render :partial => "layouts/share_popup", :locals => {:video => video} %>
	</div>
</div>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/flagged.html.erb
<h2 class="text-center"> Reported Videos </h2>

<div class="row table-responsive">
	<div class="col-md-4 col-md-offset-4">
		<table class="table table-striped">
			<thead>
				<tr>
					<th colspan="2" class="text-center"> Video </th>
				</tr>
			</thead>

			<tbody>
				<% @videos.each do |video| %>
					<tr>
						<td>
							<a href="<%= video_path(video) %>"> <img src="<%= video.video.url(:thumb) %>"> </a>
						</td>
						<td>
							<a href="<%= video_path(video) %>"> <%= video.title %> </a>
						</td>

						<td><%= link_to "Remove Flag", remove_abuse_flag_video_path(video) %></td>
						<td><%= link_to "Delete", video, method: :delete, data: { confirm: "Are you sure?" } %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<%= link_to "Admin Area", admin_path %>

app/views/videos/new.html.erb
<%= render :partial => "videos/form" %>

app/views/videos/search.html.erb
<div class="row calender widget-shadow"> 
	<div class="col-lg-10 col-md-12 col-sm-12">
		<h3 class="title"> Search Results </h3>

		<% if @videos.empty? %>
			<div class="card alert">
				Sorry, your search matches no results. Please try again with more keywords.
			</div>
		<% end %>

		<% @videos.each do |video| %>

			<div class="card cards">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12">
						<div class="col-lg-4 col-md-12 col-sm-12 text-center">
							<figure>
								<a href="<%= video_path(video) %>">
									<img src="<%= video.video.url(:thumb) %>" alt="" class="dummy img-responsive">
								</a>
							</figure>
						</div>
						<div class="col-lg-8 col-md-12 col-sm-12 porro">
							<h4>
								<a href="<%= video_path(video) %>">
									<%= video.title %>
								</a>
							</h4>
							<p>
								<strong>About: </strong> <%= video.description %>
							</p>
							<p>
								<strong>Views: </strong>
								<span class="fa fa-user"></span>
								<span class="tags"> <%= video.impressionist_count %> </span>
							</p>
							<p>
								<strong> Upload: </strong>
								<span class="fa fa-clock-o"></span>
								<span class="tags"> <%= timeago(video.created_at) %> </span>
							</p>

							<p>
								<strong>Rating: </strong>
								<span id="stars-default" class="rating-bar" data-rating="<%= video.total_rating %>">
									<input type=hidden name"rating">
								</span>
							</p>
							<p>
								<strong>Subscribe: </strong>
								<span class="fa fa-envelope"></span>
								<span class="tags"> <%= video.user.being_followed_by.length %> </span>
							</p>
							<div class="comment">
								<strong>Comment: </strong>
								<span class="price-text-color fa fa-comment"></span>
								<span class="tags"> <%= video.comments.length %> </span>
							</div>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

<%= render :partial => "layouts/pagination", :locals => {:collection => @videos} unless @videos.empty? %>

app/views/videos/setting.html.erb
<h2 class="text-center"> All Videos </h2>

<div class="row table-responsive">
	<div class="col-md-4 col-md-offset-4">
		<table class="table table-striped">
			<thead>
				<tr>
					<th colspan="2" class="text-center"> Video </th>
					<th colspan="2" class="text-center"> Controls </th>
				</tr>
			</thead>

			<tbody>
				<% @videos.each do |video| %>
					<tr>
						<td>
							<a href="<%= video_path(video) %>"> <img src="<%= video.video.url(:thumb) %>"> </a>
						</td>
						<td>
							<a href="<%= video_path(video) %>"> <%= video.title %> </a>
						</td>

						<td><%= link_to "Edit", edit_video_path(video) %></td>
						<td><%= link_to "Destroy", video, method: :delete, data: { confirm: "Are you sure?" } %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>

app/views/videos/spoop_of_the_month.html.erb
<h2 class="text-center"> Spooph of the Month Videos </h2>

<div class="row table-responsive">
	<div class="col-md-4 col-md-offset-4">
		<table class="table table-striped">
			<thead>
				<tr>
					<th colspan="2" class="text-center"> Video </th>
				</tr>
			</thead>

			<tbody>
				<% @videos.each do |video| %>
					<tr>
						<td>
							<a href="<%= video_path(video) %>"> <img src="<%= video.video.url(:thumb) %>"> </a>
						</td>
						<td>
							<a href="<%= video_path(video) %>"> <%= video.title %> </a>
						</td>
						<td> <%= video.impressionist_count %> </td>
						<td> <%= video.created_at.strftime("%B, %d %Y") %> </td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/videos/spoop_of_the_year.html.erb
<h2 class="text-center"> Spooph of the Year Videos </h2>

<div class="row table-responsive">
	<div class="col-md-4 col-md-offset-4">
		<table class="table table-striped">
			<thead>
				<tr>
					<th colspan="2" class="text-center"> Video </th>
				</tr>
			</thead>

			<tbody>
				<% @videos.each do |video| %>
					<tr>
						<td>
							<a href="<%= video_path(video) %>"> <img src="<%= video.video.url(:thumb) %>"> </a>
						</td>
						<td>
							<a href="<%= video_path(video) %>"> <%= video.title %> </a>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>