config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
	resources :users do
		member do
			get "profile"
			post "status"

			get "profile/edit" => "users#edit"
		end

		collection do
			post "follow"
		end
	end

	root "pages#home"
	
	get "/home" => "pages#home"
	get "/admin" => "pages#admin"

	get "/about" => "pages#about"
	get "/contact" => "pages#contact"
	get "/faq" => "pages#faq"
	get "/privacy" => "pages#privacy"
	
	post "/withdraw" => "pages#withdraw"

	resources :videos do
		collection do
			get "setting"
			get "favourite"

			get "spoop_of_the_month"
			get "spoop_of_the_year"
			
			get "flagged"

			post "rate"

			get "search"
		end

		member do
			get "like"
			
			get "report_abuse"
			get "remove_abuse_flag"
		end
	end

	resources :comments

	resources :themes
	
	resources :messages do
		collection do
			get "inbox"
			get "sent"
			get "trash"
		end
	end
	
	resources :pledges do
		collection do
			get "cart"
			post "charges"
		end
	end

	resources :subscriptions

	resources :channels do
		member do
			get "subscribe"
		end
	end

	resources :user_status_comments

	resources :user_statuses do
		member do
			get "like"
			get "share"
		end
	end
end

app/views/layouts/_ads_placeholder.html.erb
<div class="banner-ad">
	<a href="#">
		<img src="<%= image_url("demoad.jpg") %>" alt="advertisement">
	</a>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<p> &copy; 2016 All Rights Reserved </p>
			<ul class="footer-menu">
				<li><a href="<%= about_path %>"> ABOUT </a></li>
				<li><a href="<%= faq_path %>"> FAQ </a></li>
				<li><a href="<%= privacy_path %>"> TERMS & PRIVACY </a></li>
				<li><a href="<%= contact_path %>"> CONTACT </a></li>
			</ul>
		</div>
	</div>
</div>

<div class="go-top">
	<a href="#top">
		<i class="fa fa-angle-up"></i>
	</a>
</div>

app/views/layouts/_forget_password_popup.html.erb
<div class="popup popup-forgot" data-popup="popup-forgot">
	<div class="popup-close-overlay" data-popup="popup-forgot" data-popup-close="popup-forgot"> </div>
	<div class="popup-outer">
		<div class="popup-inner">
			<%= render :template => "devise/passwords/new" %>
			<a class="popup-close" data-popup-close="popup-forgot">x</a> 
		</div>
	</div>
</div>

app/views/layouts/_left_menu.html.erb
<div class="sidebar" role="navigation">
	<div class="navbar-collapse">
		<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
			<ul class="nav" id="side-menu">
				<div class="go-spo-btn">
					<% if current_user %>
						<a class="btn" href="<%= new_subscription_path %>">
							<img src="<%= image_url("s.png") %>">poophalicious
						</a>
					<% end %>
				</div>
				
				<li>
					<a href="<%= home_path %>" class="home">
						<i class="fa fa-home nav_icon"></i>Home
					</a>
				</li>

				<li>
					<a href="<%= spoop_of_the_year_videos_path %>">
						<i class="fa fa-trophy nav_icon"></i>Spooph Of the Year
					</a>
				</li>
				<li>
					<a href="<%= spoop_of_the_month_videos_path %>">
						<i class="fa fa-trophy nav_icon"></i>Spooph Of the Month
					</a>
				</li>

				<% if current_user %>
					<li>
						<a href="<%= inbox_messages_path %>">
							<i class="fa fa-inbox nav_icon"></i> Mail Box
							<% unread_messages = current_user.received_messages.unread_messages %>
							<% if unread_messages.length > 0 %>
								<span class="badge"> <%= unread_messages.length %> </span>
							<% end %>
							<span class="fa arrow"></span>
						</a>
						<ul class="nav nav-second-level collapse">
							<li>
								<a href="<%= inbox_messages_path %>">
									<i class="fa fa-arrow-circle-down nav_icon"></i> Inbox
								</a>
							</li>
							<li>
								<a href="<%= sent_messages_path %>">
									<i class="fa fa-arrow-circle-up nav_icon"></i> Sent
								</a>
							</li>
							<li>
								<a href="<%= trash_messages_path %>">
									<i class="fa fa-trash nav_icon"></i> Trash
								</a>
							</li>
						</ul>
					</li>

					<li>
						<a href="<%= cart_pledges_path %>">
							<i class="fa fa-shopping-cart nav_icon"></i>Shopping Cart
						</a>
					</li>
				<% end %>

				<% @themes.all.each do |theme| %>
					<li>
						<a href="<%= theme_path(theme.id) %>">
							<i class="<%= theme.html_class %>"></i>
							<%= theme.name %>
						</a>
					</li>
				<% end %>

				<% if request.user_agent =~ /Mobile|webOS/ %>
					<li class="app-store">
						<a href="#">
							<img src="<%= image_url("apple.png") %>" alt="Apple Store">
						</a>
					</li>
					<li class="app-store">
						<a href="#">
							<img src="<%= image_url("android.png") %>" alt="Android Store">
						</a>
					</li>
					<li class="app-store">
						<a href="#">
							<img src="<%= image_url("windows.png") %>" alt="Windows Store">
						</a>
					</li>
				<% end %>
			</ul>
		</nav>

	</div>
</div>

app/views/layouts/_pagination.html.erb
<div class="row">
	<div class="col-lg-10 col-md-12 col-sm-12">
		<div class="pagination-full">
			<nav>
				<%= will_paginate(collection, :renderer => PaginationListLinkRenderer) %>
			</nav>
		</div>
	</div>
</div>

app/views/layouts/_share_popup.html.erb
<div class="popup share" data-popup="popup-share">
	<div class="popup-close-overlay" data-popup="popup-share" data-popup-close="popup-share"> </div>

	<div class="popup-outer">
		<div class="popup-inner">
			<div class="main-page login-page ">
				<div class="widget-shadow">
					
					<div class="login-top">
						<h4>Share on your favorite social media network</h4>
					</div>

					<div class="login-body">
						<!-- <div class="addthis_sharing_toolbox"></div> -->
						<%= social_share_button_tag(video.title, :url => video_url(video), :image => video.video.url(:medium), :desc => video.description, :via => "Spooph.com") %>
					</div>
				</div>
			</div>

			<a class="popup-close" data-popup-close="popup-share">x</a> 
		</div>
	</div>
</div>

app/views/layouts/_sign_in_popup.html.erb
<div class="popup popup-login" data-popup="popup-login">
	<div class="popup-close-overlay" data-popup="popup-login" data-popup-close="popup-login">
	</div>
	<div class="popup-outer">
		<div class="popup-inner">
			<%= render :template => "devise/sessions/new" %>
			<a class="popup-close" data-popup-close="popup-login">x</a> 
		</div>
	</div>
</div>

app/views/layouts/_sign_up_popup.html.erb
<div class="popup popup-signup" data-popup="popup-signup">
	<div class="popup-close-overlay" data-popup="popup-signup" data-popup-close="popup-signup">
	</div>
	<div class="popup-outer">
		<div class="popup-inner">
			<%= render :template => "devise/registrations/new" %>
			<a class="popup-close" data-popup-close="popup-signup">x</a> 
		</div>
	</div>
</div>

app/views/layouts/_sticky_header.html.erb
<div class="sticky-header header-section ">
	<div class="progress-bar-height">
		<div id="myElem" class="row-fluid">
			<%= javascript_include_tag "progress_bar" %>

			<div id="messageBox" class="bar-two bar-con">
				<div class="bar" data-percent="100"></div>
			</div>
		</div>
	</div>


	<div class="header-left">
		<button id="showLeftPush">
			<i class="fa fa-bars"></i>
		</button>

		<div class="logo">
			<a href="<%= root_path %>">
				<img class="img-responsive" src="<%= image_url("logo.png") %>">
			</a>
			<!-- <p class="slogan"><%= current_user.email if current_user %></p> -->
			<p class="slogan">Real People. Real Stuff. Real Funny</p>
		</div>

		<div class="search-box">
			<%= render "videos/search_form" %>
		</div>
		<div class="clearfix"></div>
	</div>


	<div class="col-md-3 col-sm-3 col-xs-6 a-top-btn1">
		<div class="profile_details_left">
			<% if current_user %>
				<a class="pop-click upload-click" data-popup-open="popup-upload" data-toggle="modal">
					<button class="btn btn-default uploads">
						<i class="fa fa-upload"></i> &nbsp; Upload
					</button>
				</a>

				<div class="btn-group">
					<button type="button" class="btn btn-default dropdown-toggle uploads" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-cogs"></i> &nbsp; Account
						<span class="caret"></span>
					</button>
					<ul class="dropdown-menu">
						<li>
							<a href="<%= profile_user_path(current_user) %>">
								<i class="fa fa-user"></i> &nbsp; My Profile
							</a>
						</li>
						<li>
							<a href="<%= inbox_messages_path %>">
								<i class="fa fa-inbox"></i> &nbsp; Mail Box
							</a>
						</li>
						<li role="separator" class="divider"> </li>
						<li>
							<a href="<%= destroy_user_session_path %>" data-method="delete">
								<i class="fa fa-sign-out"></i> &nbsp; Logout
							</a>
						</li>
					</ul>
				</div>
			<% end %>
			<div class="clearfix"></div>
		</div>
		

		<div class="profile_details">
			<% unless current_user %>
				<a class="pop-click sign-up-click" data-popup-open="popup-signup">
					<button class="btn btn-default signup_button SignUp">
						<i class="fa fa-user"></i> &nbsp; Sign Up
					</button>
				</a>

				<a class="pop-click signin-click" data-popup-open="popup-login">
					<button class="btn btn-default signup_button">
						<i class="fa fa-lock"></i> &nbsp; Signin
					</button>
				</a>
			<% end %>
		</div>

		<div class="clearfix"></div>
	</div>

	<div class="header-right col-md-2 col-sm-2 col-xs-6">
		<ul class="social-bar">
			<li> <a href="#"><i class="fa fa-facebook-square fa-2"></i></a></li>
			<li> <a href="#"><i class="fa fa-twitter-square fa-2"></i></a></li>
			<li> <a href="#"><i class="fa fa-google-plus-square fa-2"></i></a></li>
		</ul>
		<div class="clearfix"></div>
		
		<div class="total-spledges">
			Total Spledges:
			<span class="green"> <%= Pledge.overall_pledged_amount %> </span>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="clearfix"></div>
</div>

<%= render :partial => "layouts/sign_in_popup" %>
<%= render :partial => "layouts/sign_up_popup" %>
<%= render :partial => "layouts/forget_password_popup" %>
<%= render :partial => "videos/new_form" %>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
	<title> Spooph </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<% if @main_video %>
		<meta property="fb:app_id" content="<%= FACEBOOK_CONFIG[:app_id] %>">
		<meta property="og:type" content="video">
		<meta property="og:url"	content="<%= video_url(@main_video) %>">
		<meta property="og:title" content="<%= @main_video.title %>">
		<meta property="og:description" content="<%= @main_video.description %>">
		<meta property="og:image" content="<%= root_url + @main_video.video.url(:large) %>">
	<% end %>

	<%= stylesheet_link_tag	"application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

	<link href="//fonts.googleapis.com/css?family=Roboto+Condensed:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css">
</head>


<body class="cbp-spmenu-push" id="top">
	<div class="main-content">
		
		<%= render :partial => "layouts/left_menu" %>
		<%= render :partial => "layouts/sticky_header" %>

		<div id="page-wrapper">
			<% unless request[:controller] == "users" and ["profile", "edit"].include?(request[:action]) %>
				<%= render :partial => "layouts/ads_placeholder" %>
			<% end %>

			<div class="main-page">
				<% flash.each do |name, msg| %>
					<%= content_tag :div, msg, class: "alert alert-success card" %>
				<% end %>
				<%= yield %>
				<div class="clearfix"></div>
			</div>
		</div>

		<%= render :partial => "layouts/footer" %>
	</div>

	<%= javascript_include_tag "jquery_bottom" %>
</body>
</html>